name: Update Image Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 1 * *'

jobs:
  update_cache:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore image_cache.json from cache
        uses: actions/cache/restore@v4
        id: image-cache-restore
        with:
          path: image_cache.json
          key: image-cache-v1
          restore-keys: |
            image-cache-

      - name: Log cache restore result
        run: |
          if [ -f image_cache.json ]; then
            echo "Cache restored: image_cache.json exists."
          else
            echo "No cache restored: image_cache.json not found."
          fi

      - name: Install dependencies
        run: npm install

      - name: Run script to update image cache
        run: node update-image-cache.js

      - name: Save image_cache.json to cache
        uses: actions/cache/save@v4
        with:
          path: image_cache.json
          key: image-cache-v1

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changes
        shell: bash
        run: |
          if [ -f image_cache.json ]; then
            git add image_cache.json
            if git diff --staged --quiet; then
              echo "No changes to commit in image_cache.json"
            else
              git commit -m "Update image cache [skip ci]" -m "Обновлен файл image_cache.json через GitHub Actions."
              git push || echo "Push failed (possibly due to race condition)."
              echo "image_cache.json committed and pushed."
            fi
          else
            echo "image_cache.json does not exist; skipping commit."
